# Generated by Django 5.2.8 on 2025-11-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(max_length=100)),
                ('national_code', models.CharField(max_length=20, unique=True)),
                ('id_card_number', models.CharField(max_length=20, unique=True)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('home_phone_number', models.CharField(max_length=20)),
                ('transition', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
