# Generated by Django 5.2.8 on 2025-11-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_student_clas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.CharField(max_length=20),
        ),
    ]
