# Generated by Django 5.2.8 on 2025-12-08 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_manageruser_student_teacheruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='Profile.teacheruser'),
        ),
        migrations.AddField(
            model_name='teacheruser',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students', to='Profile.student'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9a-zA-z_\\u0600-\\u06FF\\s]+$')]),
        ),
    ]
