# Generated by Django 5.2.8 on 2025-12-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_remove_student_classes_schoolclass_student_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classes',
        ),
    ]
