# Generated by Django 5.2.8 on 2025-12-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_remove_student_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='clas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
