# Generated by Django 5.2.8 on 2025-12-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_student_clas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='clas',
        ),
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='students', to='Profile.schoolclass'),
        ),
    ]
