# Generated by Django 5.2.8 on 2025-12-22 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('lesson_pdf', models.FileField(blank=True, null=True, upload_to='lessons_pdfs/')),
                ('example_pdf', models.FileField(blank=True, null=True, upload_to='example_pdfs/')),
                ('openai_lesson_file_id', models.CharField(blank=True, default='', max_length=120)),
                ('openai_example_file_id', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_json', models.JSONField()),
                ('raw_output_text', models.TextField(blank=True, default='')),
                ('openai_response_id', models.CharField(blank=True, default='', max_length=120)),
                ('usage_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bundle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='question.analysisbundle')),
            ],
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('instruction_text', models.TextField()),
                ('schema_json', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.AddField(
            model_name='analysisbundle',
            name='prompt_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundles', to='question.prompttemplate'),
        ),
    ]
