# Generated by Django 5.2.8 on 2025-12-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisbundle',
            name='model_name',
            field=models.CharField(blank=True, default='gpt-4o-mini', max_length=120),
        ),
    ]
