# Generated by Django 5.2.8 on 2025-12-26 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='hassubquestion',
            new_name='has_subquestion',
        ),
    ]
