# Generated by Django 5.2.8 on 2025-12-30 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_remove_student_clas_student_classes'),
        ('question', '0011_alter_exam_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='question.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_participations', to='Profile.student')),
            ],
            options={
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='taken_exams', through='question.ExamParticipation', to='Profile.student'),
        ),
    ]
