# Generated by Django 5.2.8 on 2025-12-30 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_remove_student_clas_student_classes'),
        ('question', '0013_studentanswer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentAnswer',
            new_name='StudentQuestionResult',
        ),
    ]
