# Generated by Django 5.2.8 on 2025-12-31 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_rename_studentanswer_studentquestionresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSnapShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='question.exam')),
            ],
        ),
    ]
