# Generated by Django 5.2.8 on 2026-01-06 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0015_examsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisbundle',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_bundles', to='question.exam'),
        ),
        migrations.AddField(
            model_name='analysisbundle',
            name='input_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisbundle',
            name='stage',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
