# Generated by Django 5.2.8 on 2026-02-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0016_analysisbundle_exam_analysisbundle_input_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisbundle',
            name='stage',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('success', 'Success'), ('failure', 'Failure')], default='stage1', max_length=120),
        ),
    ]
