# Generated by Django 5.2.8 on 2026-02-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0017_alter_analysisbundle_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisbundle',
            name='status',
            field=models.CharField(choices=[('stage1', 'Stage 1'), ('stage2', 'Stage 2'), ('stage3', 'Stage 3')], default='stage1', max_length=20),
        ),
    ]
