# Generated by Django 5.2.8 on 2026-02-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0019_prompttemplate_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='stage',
            field=models.CharField(blank=True, choices=[('stage1', 'Stage 1'), ('stage2', 'Stage 2'), ('stage3', 'Stage 3')], default='stage1', max_length=30, null=True),
        ),
    ]
